local FontFace = {

	-- Every font in existance, needs a better loop system for if fromName font is made. Much as a proof of concept for now.
	-- [[<font family="rbxasset://fonts/families/_FAMILY_.json">_NAME_</font>]]

	{Id = "AccanthisADFStd",
		Font = Font.fromName("AccanthisADFStd"),
		Text = [[<font family="rbxasset://fonts/families/AccanthisADFStd.json">Accanthis</font>]]},
	{Id = "AmaticSC",
		Font = Font.fromName("AmaticSC"),
		Text = [[<font family="rbxasset://fonts/families/AmaticSC.json">Amatic SC</font>]]},
	{Id = "Arial",
		Font = Font.fromName("Arial"),
		Text = [[<font family="rbxasset://fonts/families/Arial.json">Arial</font>]]},
	{Id = "Balthazar",
		Font = Font.fromName("Balthazar"),
		Text = [[<font family="rbxasset://fonts/families/Balthazar.json">Balthazar</font>]]},
	{Id = "Bangers",
		Font = Font.fromName("Bangers"),
		Text = [[<font family="rbxasset://fonts/families/Bangers.json">Bangers</font>]]},
	{Id = "ComicNeueAngular",
		Font = Font.fromName("ComicNeueAngular"),
		Text = [[<font family="rbxasset://fonts/families/ComicNeueAngular.json">Comic Neue</font>]]},
	{Id = "Creepster",
		Font = Font.fromName("Creepster"),
		Text = [[<font family="rbxasset://fonts/families/Creepster.json">Creepster</font>]]},
	{Id = "DenkOne",
		Font = Font.fromName("DenkOne"),
		Text = [[<font family="rbxasset://fonts/families/DenkOne.json">DenkOne</font>]]},
	{Id = "Fondamento",
		Font = Font.fromName("Fondamento"),
		Text = [[<font family="rbxasset://fonts/families/Fondamento.json">Fondamento</font>]]},
	{Id = "FredokaOne",
		Font = Font.fromName("FredokaOne"),
		Text = [[<font family="rbxasset://fonts/families/FredokaOne.json">FredokaOne</font>]]},
	{Id = "GothamSSm",
		Font = Font.fromName("GothamSSm"),
		Text = [[<font family="rbxasset://fonts/families/GothamSSm.json">Gotham SSm</font>]]},
	{Id = "GrenzeGotisch",
		Font = Font.fromName("GrenzeGotisch"),
		Text = [[<font family="rbxasset://fonts/families/GrenzeGotisch.json">Grenze Gotisch	</font>]]},
	{Id = "Guru",
		Font = Font.fromName("Guru"),
		Text = [[<font family="rbxasset://fonts/families/Guru.json">Guru</font>]]},
	{Id = "HighwayGothic",
		Font = Font.fromName("HighwayGothic"),
		Text = [[<font family="rbxasset://fonts/families/HighwayGothic.json">Highway Gothic</font>]]},
	{Id = "Inconsolata",
		Font = Font.fromName("Inconsolata"),
		Text = [[<font family="rbxasset://fonts/families/Inconsolata.json">Inconsolata</font>]]},
	{Id = "IndieFlower",
		Font = Font.fromName("IndieFlower"),
		Text = [[<font family="rbxasset://fonts/families/IndieFlower.json">Indie Flower</font>]]},
	{Id = "JosefinSans",
		Font = Font.fromName("JosefinSans"),
		Text = [[<font family="rbxasset://fonts/families/JosefinSans.json">Josefin Sans</font>]]},
	{Id = "Jura",
		Font = Font.fromName("Jura"),
		Text = [[<font family="rbxasset://fonts/families/Jura.json">Jura</font>]]},
	{Id = "Kalam",
		Font = Font.fromName("Kalam"),
		Text = [[<font family="rbxasset://fonts/families/Kalam.json">Kalam</font>]]},
	{Id = "LuckiestGuy",
		Font = Font.fromName("LuckiestGuy"),
		Text = [[<font family="rbxasset://fonts/families/LuckiestGuy.json">Luckiest Guy</font>]]},
	{Id = "Merriweather",
		Font = Font.fromName("Merriweather"),
		Text = [[<font family="rbxasset://fonts/families/Merriweather.json">Merriweather</font>]]},
	{Id = "Michroma",
		Font = Font.fromName("Michroma"),
		Text = [[<font family="rbxasset://fonts/families/Michroma.json">Michroma</font>]]},
	{Id = "Nunito",
		Font = Font.fromName("Nunito"),
		Text = [[<font family="rbxasset://fonts/families/Nunito.json">Nunito</font>]]},
	{Id = "Oswald",
		Font = Font.fromName("Oswald"),
		Text = [[<font family="rbxasset://fonts/families/Oswald.json">Oswald</font>]]},
	{Id = "PatrickHand",
		Font = Font.fromName("PatrickHand"),
		Text = [[<font family="rbxasset://fonts/families/PatrickHand.json">Patrick Hand</font>]]},
	{Id = "PermanentMarker",
		Font = Font.fromName("PermanentMarker"),
		Text = [[<font family="rbxasset://fonts/families/PermanentMarker.json">Preduring Marker</font>]]},
	{Id = "PressStart2P",
		Font = Font.fromName("PressStart2P"),
		Text = [[<font family="rbxasset://fonts/families/PressStart2P.json">PressStart2P</font>]]},
	{Id = "Roboto",
		Font = Font.fromName("Roboto"),
		Text = [[<font family="rbxasset://fonts/families/Roboto.json">Roboto</font>]]},
	{Id = "RobotoCondensed",
		Font = Font.fromName("RobotoCondensed"),
		Text = [[<font family="rbxasset://fonts/families/RobotoCondensed.json">Roboto Condensed</font>]]},
	{Id = "RobotoMono",
		Font = Font.fromName("RobotoMono"),
		Text = [[<font family="rbxasset://fonts/families/RobotoMono.json">Roboto Mono</font>]]},
	{Id = "Sarpanch",
		Font = Font.fromName("Sarpanch"),
		Text = [[<font family="rbxasset://fonts/families/Sarpanch.json">Sarpanch</font>]]},
	{Id = "SourceSansPro",
		Font = Font.fromName("SourceSansPro"),
		Text = [[<font family="rbxasset://fonts/families/SourceSansPro.json">Source Sans Pro</font>]]},
	{Id = "SpecialElite",
		Font = Font.fromName("SpecialElite"),
		Text = [[<font size="12" family="rbxasset://fonts/families/SpecialElite.json">Special Elite</font>]]},
	{Id = "TitilliumWeb",
		Font = Font.fromName("TitilliumWeb"),
		Text = [[<font family="rbxasset://fonts/families/TitilliumWeb.json">Titillium Web</font>]]},
	{Id = "Ubuntu",
		Font = Font.fromName("Ubuntu"),
		Text = [[<font family="rbxasset://fonts/families/Ubuntu.json">Ubuntu</font>]]},
	{Id = "Zekton",
		Font = Font.fromName("Zekton"),
		Text = [[<font family="rbxasset://fonts/families/Zekton.json">Zekton</font>]]}

} -- Array of fonts, please fix this. I really hate this.

return FontFace