title: Signs
description: Signs is an easy-to-use, intuitive text tool plugin for creating signs, text, and labels.
show_downloads: true
remote_theme: pages-themes/primer@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
